Chaemin-L | feat: 불필요한 강제 푸시 job 제거

diff --git a/.github/git-push.yml b/.github/git-push.yml
--- a/.github/git-push.yml
+++ b/.github/git-push.yml
@@ -1,35 +1,10 @@
-name: Git push and Synchronize to deploy to vercel
+name: Synchronize to deploy to vercel
 on: 
   push:
     branches:
       - main                        
 jobs:  
-  build:
-    runs-on: ubuntu-latest
-    container: pandoc/latex 
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
-            
-      - name: Install dependencies
-        run: pnpm install
-      
-      - name: Create output
-        run: sh ./build.sh
-
-      - name: Push to forked repository
-        uses: cpina/github-action-push-to-another-repository@main
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.FORKED_REPO_TOKEN }}
-        with:
-          source-directory: 'output'
-          destination-github-username: ‘${{ secrets.GIT_USERNAME }}’
-          destination-repository-name: ‘P.P-client’
-          commit-message: ${{ github.event.commits[0].message }}
-          target-branch: main
-
   sync:
-    needs: build
     name: Sync fork with upstream/main
     runs-on: ubuntu-latest
     steps:
@@ -40,19 +15,23 @@ jobs:
           fetch-depth: 0
           token: ${{ secrets.GITHUB_TOKEN}}
 
-      - name: Fetch and Merge forked-repo changes(job;build)
-        run: |
-          git remote add forked-repo https://github.com/${{ secrets.GIT_USERNAME }}/P.P-client
-          git fetch forked-repo 
-          git merge --ff-only forked-repo/main || exit 1 # Exit if merge fails
-
       - name: Fetch upstream changes (depromeet/P.P-client)
         run: |
           git remote add upstream https://github.com/depromeet/P.P-client
           git fetch upstream
 
+      - name: Merge upstream changes
+        run: |
+          git checkout main
+          git merge --ff-only upstream/main || exit 1 # Exit if merge fails
+
       - name: Push changes to main
         run: git push
+
+      - name: Fetch forked-repo changes
+        run: |
+          git remote add forked-repo https://github.com/${{ secrets.GIT_USERNAME }}/P.P-client
+          git fetch forked-repo 
 
       - name: Push changes to forked repository
         run: |
