Chaemin-L | fix: 서로 다른 커밋 병합 옵션 추가

diff --git a/.github/workflows/git-push.yml b/.github/workflows/git-push.yml
--- a/.github/workflows/git-push.yml
+++ b/.github/workflows/git-push.yml
@@ -11,18 +11,20 @@ jobs:
       - name: Checkout main
         uses: actions/checkout@v4
 
+      - name: Fetch upstream changes (depromeet/P.P-client)
+        run: |
+          git remote add upstream https://github.com/depromeet/P.P-client
+          git fetch upstream
+          git merge --ff-only upstream main || exit 1 # Exit if merge fails
+
       - name: Set remote-url and Merge forked-repo changes
         run: |
           git remote add forked-repo https://Chaemin-L:${{ secrets.FORKED_REPO_TOKEN }}@github.com/Chaemin-L/P.P-client
           git config user.name Chaemin-L
           git config user.email chaem12@kookmin.ac.kr
-          git pull --ff-only forked-repo main || exit 1 # Exit if merge fails
+          git fetch forked-repo main || exit 1 # Exit if merge fails
+          git merge --allow-unrelated-histories forked-reppo/main
 
-      - name: Fetch upstream changes (depromeet/P.P-client)
-        run: |
-          git remote add upstream https://github.com/depromeet/P.P-client
-          git pull --ff-only upstream main || exit 1 # Exit if merge fails
- 
       - name: Push changes to forked repository
         run: |
           git push upstream main
